apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-blogging-app
  labels:
    app: fullstack-blogging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstack-blogging-app
  template:
    metadata:
      labels:
        app: fullstack-blogging-app
    spec:
      containers:
        - name: app
          image: abrahimcse/bloggingapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-blogging-app
spec:
  type: LoadBalancer
  selector:
    app: fullstack-blogging-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
